In [1]:
import matplotlib.pyplot as plt
import numpy as np
from scipy import interp, stats
import pandas as pd
import os
import sys
from tqdm import tqdm
import math

from scipy.stats import chi2_contingency
from scipy.stats import chi2, kstest, ranksums
import seaborn as sns

from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, auc, roc_auc_score, precision_recall_curve

import warnings
warnings.filterwarnings('ignore')

from edm.utils.measures import perf_measure, calculate_output_statistics

pd.set_option('display.max_columns', None)

In [2]:
def print_statistics(df_cohort):
    df_pos = df_cohort[df_cohort["outcome"] == 1]
    df_neg = df_cohort[df_cohort["outcome"] == 0]
    print(f"Shape {df_pos.shape} for outcome = 1")
    print(f"Shape {df_neg.shape} for outcome = 0")
    print(f"---")
#     SpO2	RR	HR	Temp	SBP	DBP
    def print_numeric(col):
        pos_stat = f"{df_pos[col].describe()['50%']} [{df_pos[col].describe()['25%']}-{df_pos[col].describe()['75%']}]"
        neg_stat = f"{df_neg[col].describe()['50%']} [{df_neg[col].describe()['25%']}-{df_neg[col].describe()['75%']}]"
        pos_missing = df_pos[col].isna().sum()
        neg_missing = df_pos[col].isna().sum()
#         p_val = stats.ttest_ind(df_pos[col], df_neg[col], nan_policy="omit", equal_var=False).pvalue
        w, p_val = ranksums(df_pos[col], df_neg[col])

        print(f"{col}, {pos_stat}, {pos_missing}, {neg_stat}, {neg_missing}, {p_val}")
    
    def print_binary_col(col, val_1, val_2):
        contingency_table = [
            [df_pos[df_pos[col] == val_2].shape[0], df_neg[df_neg[col] == val_2].shape[0]],
            [df_pos[df_pos[col] == val_1].shape[0], df_neg[df_neg[col] == val_1].shape[0]]
        ]

#         print(contingency_table)

        stat, p, dof, expected = chi2_contingency(contingency_table, correction=False)
#         print(stat, p, dof, expected)

#         prob = 0.95
#         critical = chi2.ppf(prob, dof)
#         if abs(stat) >= critical:
#             print(f"Dependent (reject H0) at {stat}")
#         else:
#             print(f"Independent (fail to reject H0) at {stat}")

        pos_f = df_pos[df_pos[col] == val_1].shape[0]
        pos_m = df_pos[df_pos[col] == val_2].shape[0]
        neg_f = df_neg[df_neg[col] == val_1].shape[0]
        neg_m = df_neg[df_neg[col] == val_2].shape[0]
        pos_f_missing = df_pos[df_pos[col] == val_1][col].isna().sum()
        neg_f_missing = df_neg[df_neg[col] == val_1][col].isna().sum()
        pos_m_missing = df_pos[df_pos[col] == val_2][col].isna().sum()
        neg_m_missing = df_neg[df_neg[col] == val_2][col].isna().sum()
        print(f"{col} - {val_1}, {pos_f} ({round(100*pos_f/(pos_f+pos_m), 2)}), {pos_f_missing}, {neg_f} ({round(100*neg_f/(neg_f+neg_m), 2)}), {neg_f_missing}, {p}")
        print(f"{col} - {val_2}, {pos_m} ({round(100*pos_m/(pos_f+pos_m), 2)}), {pos_m_missing}, {neg_m} ({round(100*neg_m/(neg_f+neg_m), 2)}), {neg_m_missing},")
    
    def print_risk_factor(col):
        pos_missing = df_pos[col].isna().sum()
        neg_missing = df_neg[col].isna().sum()
        pval = stats.ttest_ind(df_pos[col], df_neg[col], nan_policy="omit", equal_var=False).pvalue
        print(f"{col}, {int(df_pos[col].sum())} ({round(100 * df_pos[col].sum() / (len(df_pos[col]) - int(df_pos[col].isna().sum())), 2)}), {pos_missing}, {int(df_neg[col].sum())} ({round(100 * df_neg[col].sum() / (len(df_neg[col]) - int(df_neg[col].isna().sum())), 2)}), {neg_missing}, {pval}")

    # ---
    print("Characteristic, Pos Statistic, Pos Missing, Neg Statistic, Neg Missing, p-value")
    print_numeric("Age")
    print_binary_col("Gender", "F", "M")
    print_binary_col("CC_CP_SOB", 0, 1)
    print_numeric("SpO2")
    print_numeric("RR")
    print_numeric("HR")
    print_numeric("Temp")
    print_numeric("SBP")
    print_numeric("DBP")
    print_numeric("First_trop")
    print_numeric("Max_trop")
    print_numeric("ED_LOS")
    print_numeric("First_trop_result_time-waveform_start_time")
    print_numeric("First_trop_result_time-Arrival_time")
    print_numeric("trim_length")
    print_risk_factor("Athero")
    print_risk_factor("HTN")
    print_risk_factor("HLD")
    print_risk_factor("DM")
    print_risk_factor("Obese")
    print_risk_factor("Smoking")

## Load Files

In [ ]:
df_annotated_manual = pd.read_csv("/deep/group/ed-monitor/patient_data_v9/consolidated.filtered.csv")
print(df_annotated_manual.shape)
df_annotated_manual.head(1)

In [3]:
df_annotated_manual.describe()

,MRN,patient_id,visit_length_sec,data_length_sec,data_available_offset_sec,data_start_offset_sec,recommended_trim_start_sec,recommended_trim_end_sec,II_available,Pleth_available,Resp_available,notes,Unnamed: 0,CSN,Age,ED_LOS,Arrival_to_roomed,CC_CP_SOB,SpO2,RR,HR,Temp,SBP,DBP,CSN_char,Athero,HTN,HLD,DM,Obese,Smoking,DVT_PE,Malignancy,First_trop,First_pos_trop,Max_trop,Case_for_train,Case_for_test,First_trop_result_time-Arrival_time,First_trop_result_time-Roomed_time,First_trop_result_time-waveform_start_time,trim_length,outcome
count,1.087400e+04,1.087400e+04,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.0,10874.000000,10874.000000,0.0,10874.000000,1.087400e+04,10874.000000,10843.000000,10874.000000,10874.000000,10863.000000,10870.000000,10870.000000,10086.000000,10860.000000,10860.000000,1.087400e+04,6371.000000,6371.000000,6371.000000,6371.000000,6371.000000,6371.000000,6371.000000,6371.000000,10874.000000,1211.000000,10874.000000,10874.000000,4131.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000
mean,3.857428e+07,1.313021e+11,11131.881552,10661.388974,26075.043314,25839.449513,407.470112,9242.950156,1.0,0.993379,0.981056,NaN,10930.520416,1.313021e+11,61.981975,6.278423,25.698639,0.342928,97.779435,18.932843,87.241490,36.755175,139.179098,79.558195,1.313021e+11,0.213938,0.329776,0.269345,0.243133,0.075812,0.044263,0.037200,0.035002,0.084506,0.866468,0.102554,0.097204,0.110627,7866.687511,6324.769174,5999.526025,8835.480044,0.097204
std,2.929239e+07,6.431649e+06,6826.062703,6738.246460,45225.541472,45365.194727,799.174276,6352.919691,0.0,0.081105,0.136334,NaN,5780.374996,6.431649e+06,19.127103,2.910171,32.633468,0.474710,3.135959,3.908124,20.962279,0.534507,25.325033,16.639474,6.431649e+06,0.410116,0.470168,0.443655,0.429008,0.264718,0.205695,0.189266,0.183800,1.105810,3.349298,1.171847,0.296249,0.313708,4036.329695,3677.557634,3703.599414,6345.056454,0.296249
min,7.088000e+03,1.312915e+11,60.000000,60.000000,0.000000,-10026.000000,5.000000,50.000000,1.0,0.000000,0.000000,NaN,1232.000000,1.312915e+11,13.000000,0.350000,0.000000,0.000000,50.000000,7.000000,0.000000,28.800000,47.000000,0.000000,1.312915e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.056000,0.000000,0.000000,0.000000,2100.000000,180.000000,109.000000,15.000000,0.000000
25%,1.377968e+07,1.312968e+11,6300.000000,5879.225000,0.000000,-237.000000,47.000000,4584.500000,1.0,1.000000,1.000000,NaN,5944.250000,1.312968e+11,48.000000,4.320000,3.000000,0.000000,97.000000,17.000000,72.000000,36.500000,122.000000,69.000000,1.312968e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080500,0.000000,0.000000,0.000000,5580.000000,4560.000000,4260.000000,4139.000000,0.000000
50%,2.841252e+07,1.313014e+11,9960.000000,9540.000000,926.500000,926.500000,140.000000,8078.000000,1.0,1.000000,1.000000,NaN,10892.000000,1.313014e+11,64.000000,5.820000,17.000000,0.000000,99.000000,18.000000,85.000000,36.700000,138.000000,79.000000,1.313014e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.139000,0.000000,0.000000,0.000000,6960.000000,5580.000000,5306.000000,7665.500000,0.000000
75%,7.614112e+07,1.313080e+11,15060.000000,14463.250000,36655.250000,36655.250000,435.000000,12608.000000,1.0,1.000000,1.000000,NaN,15769.750000,1.313080e+11,77.000000,7.650000,32.000000,1.000000,100.000000,20.000000,99.000000,36.900000,154.000000,89.000000,1.313080e+11,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.368500,0.000000,0.000000,0.000000,8880.000000,7080.000000,6757.750000,12195.000000,0.000000
max,9.957590e+07,1.313151e+11,78960.000000,59552.400000,683628.000000,683628.000000,17502.000000,57920.000000,1.0,1.000000,1.000000,NaN,23214.000000,1.313151e+11,120.000000,50.620000,728.000000,1.000000,100.000000,75.000000,254.000000,40.200000,265.000000,190.000000,1.313151e+11,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,40.000000,40.000000,40.000000,1.000000,1.000000,88500.000000,88500.000000,87737.000000,57867.000000,1.000000

In [4]:
df_pos = df_annotated_manual[df_annotated_manual["outcome"] == 1]
print(df_pos.shape)
df_neg = df_annotated_manual[df_annotated_manual["outcome"] == 0]
print(df_neg.shape)

(1057, 79)
(9817, 79)

## Statistics

In [19]:
print_statistics(df_annotated_manual)

Shape (1057, 79) for outcome = 1
Shape (9817, 79) for outcome = 0
---
Characteristic, Pos Statistic, Pos Missing, Neg Statistic, Neg Missing, p-value
Age, 71.0 [59.0-83.0], 0, 63.0 [47.0-76.0], 0, 6.4975853236443074e-43
Gender - F, 444 (42.09), 0, 5136 (52.32), 0, 2.587171245842113e-10
Gender - M, 611 (57.91), 0, 4680 (47.68), 0,
CC_CP_SOB - 0, 644 (60.93), 0, 6501 (66.22), 0, 0.0005697700577133987
CC_CP_SOB - 1, 413 (39.07), 0, 3316 (33.78), 0,
SpO2, 98.0 [96.0-100.0], 2, 99.0 [97.0-100.0], 2, 3.9983671651375525e-13
RR, 18.0 [18.0-22.0], 1, 18.0 [16.0-20.0], 1, 7.702467483918752e-19
HR, 87.0 [73.0-106.0], 1, 84.0 [72.0-99.0], 1, 3.283582954343181e-05
Temp, 36.7 [36.5-36.9], 65, 36.7 [36.5-36.9], 65, 0.038499824253701444
SBP, 137.0 [116.0-156.0], 3, 138.0 [123.0-153.0], 3, 0.02133306751585782
DBP, 78.0 [66.0-91.0], 3, 79.0 [69.0-89.0], 3, 0.13611389432796914
First_trop, 0.124 [0.072-0.327], 0, 0.0 [0.0-0.0], 0, 0.0
Max_trop, 0.164 [0.091-0.492], 0, 0.0 [0.0-0.0], 0, 0.0
ED_LOS, 6.47 [4.8549999999999995-8.3], 7, 5.75 [4.27-7.57], 7, 2.6811728481189483e-18
First_trop_result_time-waveform_start_time, 5460.0 [4440.0-6960.0], 0, 5280.0 [4259.0-6720.0], 0, 0.0004886014015180989
First_trop_result_time-Arrival_time, 6720.0 [5280.0-8460.0], 0, 6960.0 [5640.0-8880.0], 0, 1.1019523444992148e-05
trim_length, 6399.0 [2809.0-11230.0], 0, 7802.0 [4292.0-12299.0], 0, 2.654124278616294e-11
Athero, 210 (31.91), 399, 1153 (20.18), 4104, 9.587068731952986e-10
HTN, 261 (39.67), 399, 1840 (32.21), 4104, 0.00021507016203822245
HLD, 202 (30.7), 399, 1514 (26.5), 4104, 0.026763511124936145
DM, 181 (27.51), 399, 1368 (23.95), 4104, 0.05211369200101317
Obese, 43 (6.53), 399, 440 (7.7), 4104, 0.2560976293205908
Smoking, 27 (4.1), 399, 255 (4.46), 4104, 0.6608959909891639

In [24]:
# First trop neg?
tot_patient = df_pos.shape[0]
mi_patients = df_pos[df_pos["First_trop"] > 0.055].shape[0]
print(f"")
print(f"Number of patients who had first trop pos {mi_patients}/{tot_patient} ({100*mi_patients/tot_patient}%)")
print(f"Number of patients who had first trop neg {(tot_patient-mi_patients)}/{tot_patient} ({100*(tot_patient-mi_patients)/tot_patient}%)")

Number of patients who had first trop pos 957/1057 (90.53926206244087%)
Number of patients who had first trop neg 100/1057 (9.460737937559129%)

In [26]:
# How long did MI patients who had first trop neg have to wait until pos trop result?
from dateutil import parser

wait_times = []
for i, row in df_pos[df_pos["First_trop"] <= 0.055].iterrows():
    trop_available = parser.parse(row["Max_trop_result_time"])
    arrival_time = parser.parse(row["Arrival_time"])
    wait_times.append((trop_available - arrival_time).total_seconds())
    
print(len(wait_times))
print(f"MI patients who had first trop neg have to wait {np.mean(wait_times) / 3600} hours until first pos trop")

100
MI patients who had first trop neg have to wait 6.244333333333333 hours until first pos trop

In [32]:
# CI difference in populations
# https://www.dummies.com/education/math/statistics/creating-a-confidence-interval-for-the-difference-of-two-means-with-known-standard-deviations/

def diff_in_cols(df_pos, df_neg, col):
    acs_std = df_pos[col].describe()["std"]
    nonacs_std = df_neg[col].describe()["std"]
    ci_diff = 1.96 * math.sqrt(((acs_std ** 2) / df_pos.shape[0]) + ((nonacs_std ** 2) / df_neg.shape[0]))
    diff = df_pos[col].describe()["50%"] - df_neg[col].describe()["50%"] 
    print(f"{col} difference = {round(diff, 3)} [{round(diff - ci_diff, 3)}-{round(diff + ci_diff, 3)}]")

In [33]:
# What's the difference between bedside monitoring lengths?

diff_in_cols(df_pos, df_neg, "trim_length")

trim_length difference = -1403.0 [-1809.623--996.377]

In [34]:
# What's the difference between bedside ED stay?

diff_in_cols(df_pos, df_neg, "ED_LOS")

ED_LOS difference = 0.72 [0.53-0.91]

In [37]:
# How many were admitted to inpatient care?

inpatient_values = [
    "Admit to Inpatient", 
    "Place in Observation", 
    "Place in Observation-CDU", 
    "Transfer to Outside Facility/Hospital", 
    "Transfer to LPCH/PEC"
]

df_pos_inpatient = df_pos[df_pos["ED_dispo"].isin(inpatient_values)]
print(f"For pos, {df_pos_inpatient.shape[0]}/{df_pos.shape[0]} ({100*df_pos_inpatient.shape[0]/df_pos.shape[0]}%) patients were admitted to inpatient")

df_neg_inpatient = df_neg[df_neg["ED_dispo"].isin(inpatient_values)]
print(f"For neg, {df_neg_inpatient.shape[0]}/{df_neg.shape[0]} ({100*df_neg_inpatient.shape[0]/df_neg.shape[0]}%) patients were admitted to inpatient")

diff_in_cols(df_pos, df_neg, "ED_LOS")

For pos, 1009/1057 (95.45884578997162%) patients were admitted to inpatient
For neg, 4543/9817 (46.27686665987573%) patients were admitted to inpatient

```
> prop.test(x=c(1009, 4543), n=c(1057, 9817), correct=FALSE)

	2-sample test for equality of proportions without continuity correction

data:  c(1009, 4543) out of c(1057, 9817)
X-squared = 923.7, df = 1, p-value < 2.2e-16
alternative hypothesis: two.sided
95 percent confidence interval:
 0.4758564 0.5077832
sample estimates:
   prop 1    prop 2 
0.9545885 0.4627687 
```

## Independence

### Validate independence of test set with overall SOB dataset

In [ ]:
df_annotated_manual = pd.read_csv("/deep/group/ed-monitor/patient_data_v9/consolidated.filtered.csv")
df_annotated_manual = df_annotated_manual[(df_annotated_manual["Case_for_test"] == 1) | (df_annotated_manual["Case_for_test"] == 0)]
print(df_annotated_manual.shape)
df_annotated_manual.head(1)

In [11]:
df_annotated_manual.describe()

,MRN,patient_id,visit_length_sec,data_length_sec,data_available_offset_sec,data_start_offset_sec,recommended_trim_start_sec,recommended_trim_end_sec,II_available,Pleth_available,Resp_available,notes,Unnamed: 0,CSN,Age,ED_LOS,Arrival_to_roomed,CC_CP_SOB,SpO2,RR,HR,Temp,SBP,DBP,CSN_char,Athero,HTN,HLD,DM,Obese,Smoking,DVT_PE,Malignancy,First_trop,First_pos_trop,Max_trop,Case_for_train,Case_for_test,First_trop_result_time-Arrival_time,First_trop_result_time-Roomed_time,First_trop_result_time-waveform_start_time,trim_length,outcome
count,4.131000e+03,4.131000e+03,4131.000000,4131.000000,4131.000000,4131.000000,4131.000000,4131.000000,4131.0,4131.000000,4131.000000,0.0,4131.00000,4.131000e+03,4131.000000,4124.000000,4131.000000,4131.000000,4127.000000,4130.000000,4131.000000,3874.000000,4128.000000,4128.000000,4.131000e+03,2504.000000,2504.000000,2504.000000,2504.000000,2504.000000,2504.000000,2504.000000,2504.000000,4131.000000,549.000000,4131.000000,4131.000000,4131.000000,4131.000000,4131.000000,4131.000000,4131.000000,4131.000000
mean,3.890164e+07,1.313017e+11,10813.042847,10387.012007,26603.836601,26367.156137,362.483660,9350.035100,1.0,0.993948,0.982329,NaN,10588.51053,1.313017e+11,58.213266,5.969707,29.067538,0.902687,97.693967,19.334383,87.061002,36.772483,138.412306,79.412548,1.313017e+11,0.217652,0.314297,0.266374,0.245208,0.091853,0.046326,0.044728,0.031550,0.116148,1.020505,0.146555,0.111111,0.110627,7529.716776,5785.664488,5465.102881,8987.551440,0.111111
std,2.852888e+07,6.386840e+06,6628.510781,6520.601013,46690.710906,46829.067136,663.940054,6222.019834,0.0,0.077567,0.131769,NaN,5740.99030,6.386840e+06,18.895258,2.700004,32.076023,0.296419,3.509094,4.224885,20.259746,0.472548,23.385240,15.841262,6.386840e+06,0.412732,0.464328,0.442150,0.430296,0.288876,0.210232,0.206748,0.174832,1.308177,3.610218,1.418674,0.314308,0.313708,3251.981700,2872.287673,2897.669164,6216.777504,0.314308
min,7.088000e+03,1.312915e+11,60.000000,60.000000,0.000000,-10026.000000,5.000000,50.000000,1.0,0.000000,0.000000,NaN,1246.00000,1.312915e+11,18.000000,0.350000,0.000000,0.000000,53.000000,9.000000,9.000000,31.400000,47.000000,11.000000,1.312915e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.056000,0.000000,0.000000,0.000000,2100.000000,180.000000,148.000000,15.000000,0.000000
25%,1.487245e+07,1.312964e+11,6240.000000,5820.000000,0.000000,-263.000000,46.000000,4914.000000,1.0,1.000000,1.000000,NaN,5595.00000,1.312964e+11,44.000000,4.120000,10.000000,1.000000,97.000000,18.000000,72.000000,36.500000,123.000000,69.000000,1.312964e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.084000,0.000000,0.000000,0.000000,5580.000000,4380.000000,4080.000000,4554.000000,0.000000
50%,2.899041e+07,1.313009e+11,9660.000000,9253.000000,1265.000000,1265.000000,133.000000,8196.000000,1.0,1.000000,1.000000,NaN,10380.00000,1.313009e+11,59.000000,5.530000,20.000000,1.000000,99.000000,18.000000,85.000000,36.700000,137.000000,79.000000,1.313009e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.161000,0.000000,0.000000,0.000000,6840.000000,5340.000000,5040.000000,7824.000000,0.000000
75%,7.556713e+07,1.313076e+11,14460.000000,14063.500000,36900.000000,36900.000000,407.000000,12708.000000,1.0,1.000000,1.000000,NaN,15303.00000,1.313076e+11,73.000000,7.320000,36.000000,1.000000,100.000000,20.000000,99.000000,36.900000,152.000000,89.000000,1.313076e+11,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.449000,0.000000,0.000000,0.000000,8580.000000,6660.000000,6360.000000,12294.000000,0.000000
max,9.955426e+07,1.313133e+11,78960.000000,54098.200000,683628.000000,683628.000000,9028.000000,46074.000000,1.0,1.000000,1.000000,NaN,21473.00000,1.313133e+11,107.000000,30.120000,275.000000,1.000000,100.000000,71.000000,254.000000,39.900000,259.000000,190.000000,1.313133e+11,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,40.000000,40.000000,40.000000,1.000000,1.000000,48600.000000,48120.000000,48120.000000,44580.000000,1.000000

In [ ]:
df_annotated_manual_test = pd.read_csv("/deep/group/ed-monitor/patient_data_v9/consolidated.filtered.test.txt", sep="\t")
print(df_annotated_manual_test.shape)
df_annotated_manual_test.head(1)

In [36]:
def print_numeric_stat(df_annotated_manual, df_annotated_manual_test, col):
    x = np.array(df_annotated_manual[col], dtype=np.float)
    y = np.array(df_annotated_manual_test[col], dtype=np.float)
    statistic, pval = stats.ttest_ind(x[~np.isnan(x)], y[~np.isnan(y)], equal_var=False)
    print(f"{col}: {statistic} pval={pval}")

In [37]:
def print_cat_stat(df_annotated_manual, df_annotated_manual_test, col, mappings):
    contingency_table = []
    for k in mappings.keys():
        row = []
        
        count = 0
        for r in df_annotated_manual[col].tolist():
            if r == k:
                count += 1
        row.append(count)

        count = 0
        for r in df_annotated_manual_test[col].tolist():
            if r == k:
                count += 1
        row.append(count)

        contingency_table.append(row)
        
    stat, p, dof, expected = chi2_contingency(contingency_table, correction=False)

    prob = 0.95
    critical = chi2.ppf(prob, dof)
    if abs(stat) >= critical:
        print(f"{col}: {contingency_table} statistically significant")
    else:
        print(f"{col}: {contingency_table} not statistically significant")

In [42]:
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "Age")
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "Gender", {"F": 0, "M": 1})
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "SpO2")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "RR")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "HR")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "Temp")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "SBP")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "DBP")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "First_trop")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "Max_trop")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "ED_LOS")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "First_trop_result_time-waveform_start_time")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "First_trop_result_time-Arrival_time")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "trim_length")
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "Athero", {0: 0, 1: 1})
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "HTN", {0: 0, 1: 1})
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "HLD", {0: 0, 1: 1})
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "DM", {0: 0, 1: 1})
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "Obese", {0: 0, 1: 1})
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "Smoking", {0: 0, 1: 1})

Age: -0.0815471189210677 pval=0.9350139729115687
Gender: [[2111, 712], [2019, 643]] not statistically significant
SpO2: 0.1449359465478856 pval=0.8847745822279938
RR: -0.6037434299757884 pval=0.546077232451806
HR: 0.3043184824916402 pval=0.760912457715388
Temp: -0.8721309776977275 pval=0.3832364753214976
SBP: 0.0050405249274155075 pval=0.9959787034858913
DBP: 0.701384375054689 pval=0.4831334649096156
First_trop: -1.0973691477534222 pval=0.27262655787734447
Max_trop: -1.125362364398196 pval=0.2605823666221569
ED_LOS: -0.07051907298445818 pval=0.943786560802435
First_trop_result_time-waveform_start_time: -0.47989196235282483 pval=0.631350727296526
First_trop_result_time-Arrival_time: 0.24758566168948865 pval=0.8044774535444357
trim_length: 0.023040519027420898 pval=0.9816199461876243
Athero: [[1959, 672], [545, 182]] not statistically significant
HTN: [[1717, 601], [787, 253]] not statistically significant
HLD: [[1837, 662], [667, 192]] statistically significant
DM: [[1890, 636], [614, 218]] not statistically significant
Obese: [[2274, 779], [230, 75]] not statistically significant
Smoking: [[2388, 819], [116, 35]] not statistically significant

### Validate independence of val set with overall SOB dataset

In [ ]:
df_annotated_manual = pd.read_csv("/deep/group/ed-monitor/patient_data_v9/consolidated.filtered.val.txt", sep="\t")
print(df_annotated_manual.shape)
df_annotated_manual.head(1)

In [53]:
df_annotated_manual.describe()

,MRN,patient_id,visit_length_sec,data_length_sec,data_available_offset_sec,data_start_offset_sec,recommended_trim_start_sec,recommended_trim_end_sec,II_available,Pleth_available,Resp_available,notes,Unnamed: 0,CSN,Age,ED_LOS,Arrival_to_roomed,CC_CP_SOB,SpO2,RR,HR,Temp,SBP,DBP,CSN_char,Athero,HTN,HLD,DM,Obese,Smoking,DVT_PE,Malignancy,First_trop,First_pos_trop,Max_trop,Case_for_train,Case_for_test,First_trop_result_time-Arrival_time,First_trop_result_time-Roomed_time,First_trop_result_time-waveform_start_time,trim_length,outcome
count,1.356000e+03,1.356000e+03,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.0,1356.000000,1356.000000,0.0,1356.000000,1.356000e+03,1356.000000,1354.000000,1356.000000,1356.000000,1354.000000,1355.000000,1356.000000,1280.000000,1355.000000,1355.000000,1.356000e+03,800.000000,800.000000,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,1356.000000,182.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000
mean,3.935458e+07,1.313020e+11,10969.734513,10512.600147,27155.438053,26920.904867,355.789823,9478.182153,1.0,0.993363,0.975664,NaN,10812.224189,1.313020e+11,58.858407,6.014771,28.844395,0.891593,97.716396,19.282657,87.421829,36.764531,137.917343,79.527675,1.313020e+11,0.230000,0.302500,0.270000,0.22750,0.087500,0.051250,0.040000,0.036250,0.106477,0.818626,0.133270,0.110619,0.110619,7473.893805,5743.230088,5411.088496,9122.392330,0.110619
std,2.878697e+07,6.530540e+06,6852.995289,6654.788775,50619.709274,50748.634375,657.934726,6332.851661,0.0,0.081228,0.154148,NaN,5865.341257,6.530540e+06,18.801916,2.652992,32.656234,0.311009,3.420850,4.083394,20.423319,0.449924,22.387529,15.676373,6.530540e+06,0.421096,0.459628,0.444237,0.41948,0.282743,0.220645,0.196082,0.187029,1.193851,3.179118,1.353172,0.313776,0.313776,3236.505409,2919.640964,2942.441961,6323.283857,0.313776
min,2.213900e+05,1.312915e+11,60.000000,60.000000,0.000000,-7185.000000,5.000000,50.000000,1.0,0.000000,0.000000,NaN,1247.000000,1.312915e+11,18.000000,0.470000,0.000000,0.000000,64.000000,9.000000,38.000000,34.700000,66.000000,28.000000,1.312915e+11,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.056000,0.000000,0.000000,0.000000,2820.000000,420.000000,148.000000,20.000000,0.000000
25%,1.481883e+07,1.312965e+11,6360.000000,5929.250000,0.000000,-263.000000,44.000000,4835.500000,1.0,1.000000,1.000000,NaN,5669.750000,1.312965e+11,45.000000,4.180000,9.000000,1.000000,97.000000,18.000000,73.000000,36.500000,123.000000,69.500000,1.312965e+11,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.084000,0.000000,0.000000,0.000000,5580.000000,4440.000000,4097.250000,4563.250000,0.000000
50%,2.903682e+07,1.313013e+11,9900.000000,9496.000000,1610.000000,1610.000000,127.000000,8574.000000,1.0,1.000000,1.000000,NaN,10758.500000,1.313013e+11,59.000000,5.580000,20.000000,1.000000,99.000000,18.000000,85.000000,36.700000,137.000000,80.000000,1.313013e+11,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.145500,0.000000,0.000000,0.000000,6840.000000,5340.000000,5046.500000,8099.000000,0.000000
75%,7.608309e+07,1.313080e+11,14400.000000,14133.750000,34992.250000,34992.250000,390.250000,12834.000000,1.0,1.000000,1.000000,NaN,15773.500000,1.313080e+11,73.000000,7.415000,35.000000,1.000000,100.000000,20.000000,99.000000,36.900000,151.000000,89.000000,1.313080e+11,0.000000,1.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.384750,0.000000,0.000000,0.000000,8520.000000,6600.000000,6300.000000,12553.500000,0.000000
max,9.955426e+07,1.313133e+11,78960.000000,54098.200000,683628.000000,683628.000000,9028.000000,39579.000000,1.0,1.000000,1.000000,NaN,21469.000000,1.313133e+11,107.000000,28.620000,275.000000,1.000000,100.000000,69.000000,254.000000,39.600000,235.000000,152.000000,1.313133e+11,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,36.889000,36.889000,40.000000,1.000000,1.000000,48600.000000,48120.000000,48120.000000,39310.000000,1.000000

In [ ]:
df_annotated_manual_test = pd.read_csv("/deep/group/ed-monitor/patient_data_v9/consolidated.filtered.test.txt", sep="\t")
print(df_annotated_manual_test.shape)
df_annotated_manual_test.head(1)

In [55]:
def print_numeric_stat(df_annotated_manual, df_annotated_manual_test, col):
    x = np.array(df_annotated_manual[col], dtype=np.float)
    y = np.array(df_annotated_manual_test[col], dtype=np.float)
    statistic, pval = stats.ttest_ind(x[~np.isnan(x)], y[~np.isnan(y)], equal_var=False)
    print(f"{col}: {statistic} pval={pval}")

In [56]:
def print_cat_stat(df_annotated_manual, df_annotated_manual_test, col, mappings):
    contingency_table = []
    for k in mappings.keys():
        row = []
        
        count = 0
        for r in df_annotated_manual[col].tolist():
            if r == k:
                count += 1
        row.append(count)

        count = 0
        for r in df_annotated_manual_test[col].tolist():
            if r == k:
                count += 1
        row.append(count)

        contingency_table.append(row)
        
    stat, p, dof, expected = chi2_contingency(contingency_table, correction=False)

    prob = 0.95
    critical = chi2.ppf(prob, dof)
    if abs(stat) >= critical:
        print(f"{col}: {contingency_table} statistically significant")
    else:
        print(f"{col}: {contingency_table} not statistically significant")

In [57]:
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "Age")
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "Gender", {"F": 0, "M": 1})
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "SpO2")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "RR")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "HR")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "Temp")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "SBP")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "DBP")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "First_trop")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "Max_trop")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "ED_LOS")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "First_trop_result_time-waveform_start_time")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "First_trop_result_time-Arrival_time")
print_numeric_stat(df_annotated_manual, df_annotated_manual_test, "trim_length")
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "Athero", {0: 0, 1: 1})
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "HTN", {0: 0, 1: 1})
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "HLD", {0: 0, 1: 1})
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "DM", {0: 0, 1: 1})
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "Obese", {0: 0, 1: 1})
print_cat_stat(df_annotated_manual, df_annotated_manual_test, "Smoking", {0: 0, 1: 1})

Age: 0.8206702197157482 pval=0.4119063320485823
Gender: [[687, 712], [669, 643]] not statistically significant
SpO2: 0.28540941971372413 pval=0.775352432076268
RR: -0.8203944979663653 pval=0.41206425705507777
HR: 0.7105116689368924 pval=0.4774480557371259
Temp: -1.1620882336041958 pval=0.24530929885192615
SBP: -0.5521722206055424 pval=0.5808761064154928
DBP: 0.7644176037928548 pval=0.4446850001552457
First_trop: -1.1572396657347122 pval=0.2472950109395037
Max_trop: -1.208118861933213 pval=0.22712047967023463
ED_LOS: 0.38387931099428363 pval=0.7010980832502776
First_trop_result_time-waveform_start_time: -0.8659342409463803 pval=0.3866028890627804
First_trop_result_time-Arrival_time: -0.23935978406527025 pval=0.8108447262454463
trim_length: 0.5780481744617176 pval=0.5632796337214367
Athero: [[616, 672], [184, 182]] not statistically significant
HTN: [[558, 601], [242, 253]] not statistically significant
HLD: [[584, 662], [216, 192]] statistically significant
DM: [[618, 636], [182, 218]] not statistically significant
Obese: [[730, 779], [70, 75]] not statistically significant
Smoking: [[759, 819], [41, 35]] not statistically significant